# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-18 19:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('turn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('srank', models.PositiveIntegerField(blank=True, null=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True)),
                ('comment', models.CharField(blank=True, max_length=2048, null=True)),
                ('turn_time', models.DateTimeField(blank=True, null=True)),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portal.Member')),
                ('suggested_members', models.ManyToManyField(to='portal.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Member')),
                ('song_list', models.ManyToManyField(to='portal.Song')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='member_list',
            field=models.ManyToManyField(to='portal.Member'),
        ),
        migrations.AddField(
            model_name='group',
            name='prev_turn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portal.Turn'),
        ),
    ]
