# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 18:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.CharField(max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('turn', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('url', models.URLField()),
                ('time_added', models.DateTimeField(auto_now_add=True)),
                ('recommender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='portal.Member')),
                ('suggested_members', models.ManyToManyField(to='portal.Member')),
            ],
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turn_time', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Member')),
                ('song_list', models.ManyToManyField(through='portal.Evaluation', to='portal.Song')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='history',
            field=models.ManyToManyField(to='portal.Turn'),
        ),
        migrations.AddField(
            model_name='group',
            name='member_list',
            field=models.ManyToManyField(to='portal.Member'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Song'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='turn',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Turn'),
        ),
    ]
