# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-23 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_auto_20151221_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='srank',
            new_name='rank',
        ),
    ]
